### ISSUE TITLE
无法更新

### ISSUE THREAD

**Issue by loveqianool** [hiliqi/raccoon5#2]
```
cURL error 6: Could not resolve host: v5.xhxcms.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```
v5.xhxcms.com 无法解析。

**Comment by hiliqi** [comment]
现在不支持后台升级


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hiliqi/raccoon5"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月9日(星期天) 晚上8:49
收件人:&nbsp;"hiliqi/raccoon5"<raccoon5@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[hiliqi/raccoon5] 无法更新 (#2)





 cURL error 6: Could not resolve host: v5.xhxcms.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)  
v5.xhxcms.com 无法解析。

**Comment by loveqianool** [comment]
那把功能去掉。
